services:
  # sabnzbd:
  #   image: lscr.io/linuxserver/sabnzbd
  #   restart: unless-stopped
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=Etc/UTC
  #   volumes:
  #     - .container-data/sabnzbd:/config
  #   ports:
  #     - 10000:8080
  db:
    image: postgres
    restart: unless-stopped
    shm_size: 128m
    environment:
      - POSTGRES_USER=vttt
      - POSTGRES_PASSWORD=vttt
      - POSTGRES_DB=vignettte
    ports:
      - 5432:5432
