services:
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - .container-data/sabnzbd:/config
    ports:
      - 10000:8080
    restart: unless-stopped